【できていないこと】
ssk9597/B-Teck pull request #10
Opened 2020-09-25 04:11 UTC by ssk9597

・main.js(89行目〜92行目)があるためうまく作用しない。
こちらを消すと、ボタンが消えずに蓄積してしまう

・回答ボタンのシャッフル機能
現在全ての回答が一番下にあるため

2020-09-26 13:03 UTC, myzktkyk requested changes
動作は問題ありませんでした。
何点か指摘をしております。

2020-09-26 13:03 UTC, myzktkyk commented on JavaScript/task4/main.js
> +                    v++
おそらく for 文全体が長くなるためにこの様にされていると想像しますが
この様に整形することはあまりないです。

2020-09-26 13:03 UTC, myzktkyk commented on JavaScript/task4/main.js
> +    callAPI();
callAPI は `async` メソッドなので `await` を使ってほしいです。

2020-09-26 23:46 UTC, ssk9597 commented on JavaScript/task4/main.js
> +    let questionsArry = [];
修正しました！

2020-09-26 23:46 UTC, ssk9597 commented on JavaScript/task4/main.js
> +            const object = {
quizObjectに修正しました！

2020-09-26 23:47 UTC, ssk9597 commented on JavaScript/task4/main.js
> +            //いらないもの
コメントを修正しました

2020-09-26 23:48 UTC, ssk9597 commented on JavaScript/task4/main.js
> +                    v++
prettierで勝手にこうなってしまったので、
`printWidth: 100,`
こちらを追加し1行で表示できるようになりました。

2020-09-26 23:51 UTC, ssk9597 commented on JavaScript/task4/main.js
> +    callAPI();
申し訳ございません。
こちらの意図が理解できませんでした。
callAPIを呼び出す際にawaitをつけるともちろんエラーが出ますし、
こちらをもう少し説明していただけますでしょうか？

2020-09-27 22:08 UTC, kouki-iwahara commented on JavaScript/task4/main.js
> +    callAPI();
callAPIという関数が非同期処理を含むため、現在はasyncをつけて定義しているかと思います。
ですので、awaitを使用して呼び出さないと同期的な処理にならないという意味です。
エラーはどのようなエラーでしょうか？

2020-09-27 23:16 UTC, ssk9597 commented on JavaScript/task4/main.js
> +    callAPI();
なるほど、理解しました。

`Uncaught SyntaxError: await is only valid in async function`
エラーメッセージはこちらです。

2020-09-28 10:54 UTC, merged